/*
Created by clemens on 6/8/18.
This file is part of the software provided by ARTI
Copyright (c) 2018, ARTI
All rights reserved.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef ARTI_CONVERT_ACKERMANN_ARTI_CONVERT_ACKERMANN_NODE_H
#define ARTI_CONVERT_ACKERMANN_ARTI_CONVERT_ACKERMANN_NODE_H

#include <ros/ros.h>
#include <geometry_msgs/Twist.h>
#include <ackermann_msgs/AckermannDrive.h>

namespace arti_convert_ackermann
{
  class ArtiConvertAckermannNode
  {
  public:
    ArtiConvertAckermannNode(ros::NodeHandle nh);

  private:
    void ackermannCB(const ackermann_msgs::AckermannDrive &msg);

    ros::NodeHandle nh_;
    ros::Subscriber ackermann_sub_;
    ros::Publisher cmd_vel_pub_;
  };
}

#endif //ARTI_CONVERT_ACKERMANN_ARTI_CONVERT_ACKERMANN_NODE_H
