# These parameters describe the vehicle geometry and motor connections:

vehicle:
  steering_angle_velocity: 0.2
  axles:
    front_axle:
      position_x: 0.275
      position_y: 0.0
      wheel_diameter: 0.245
      is_steered: true
      is_driven: true
      track: 0.56
      steering_hinge_offset: 0.06
      steering_angle_max: 0.6981317008
      left_hinge_joint: front_left_hinge_joint
      left_wheel_joint: front_left_wheel_joint
      right_hinge_joint: front_right_hinge_joint
      right_wheel_joint: front_right_wheel_joint
      steering:
        type: IdealAckermannSteering
        icr_x: 0.0
        steering_joint: front_steering_joint
      steering_motor:
        transport_name: transport
        controller_id: 2
        invert_direction: true
        position_offset: 1.57
        process_noise_p: 0.1
        measurement_noise: 0.01
      left_motor:
        transport_name: transport
        controller_id: 1
        motor_poles: 15
        invert_direction: false
        velocity_correction: 0.95
      right_motor:
        transport_name: transport
        controller_id: 0
        motor_poles: 15
        invert_direction: false
        velocity_correction: 0.95

    rear_axle:
      type: IdealAckermannSteering
      position_x: -0.275
      position_y: 0.0
      wheel_diameter: 0.245
      is_steered: true
      is_driven: true
      track: 0.56
      steering_hinge_offset: 0.06
      steering_angle_max: 0.6981317008
      left_hinge_joint: rear_left_hinge_joint
      left_wheel_joint: rear_left_wheel_joint
      right_hinge_joint: rear_right_hinge_joint
      right_wheel_joint: rear_right_wheel_joint
      steering:
        type: IdealAckermannSteering
        icr_x: 0.0
        steering_joint: front_steering_joint
      steering_motor:
        transport_name: transport
        controller_id: 3
        invert_direction: true
        position_offset: 2.26
        process_noise_p: 0.1
        measurement_noise: 0.01        
      left_motor:
        transport_name: transport
        controller_id: 5
        motor_poles: 15
        invert_direction: false
        velocity_correction: 0.95
      right_motor:
        transport_name: transport
        controller_id: 4
        motor_poles: 15
        invert_direction: false
        velocity_correction: 0.95

transport_mapping:
  - transport_name: transport
    controller_id: 0
    port: '/dev/ttyACM0'

